#!/usr/bin/env node

/**
 * Builds an EPD-keyed ECO lookup table from the lichess chess-openings dist files.
 *
 * The dist/ files are generated by cloning https://github.com/lichess-org/chess-openings
 * and running `make` (requires python3 + python-chess).
 *
 * Input: dist/all.tsv (or a.tsv–e.tsv) with columns: eco, name, pgn, uci, epd
 * Output: worker/src/eco-epd.json — { [epd]: { eco, name } }
 *
 * Usage: node scripts/build-eco-epd.js /path/to/chess-openings/dist/all.tsv
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const inputPath = process.argv[2];
if (!inputPath) {
    console.error('Usage: node scripts/build-eco-epd.js <path-to-dist/all.tsv>');
    process.exit(1);
}

const text = readFileSync(resolve(inputPath), 'utf-8');
const lines = text.trim().split('\n');

// Skip header: eco\tname\tpgn\tuci\tepd
const db = {};
let count = 0;

for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split('\t');
    if (parts.length < 5) continue;

    const eco = parts[0].trim();
    const name = parts[1].trim();
    const epd = parts[4].trim();

    // Multiple openings can share the same EPD (same position, different move orders).
    // Keep the one with the longest name (most specific).
    if (!db[epd] || name.length > db[epd].name.length) {
        db[epd] = { eco, name };
    }
    count++;
}

// Also build the old ECO-code-keyed format for the frontend (with moves for prefix matching)
// This stays in eco-data.js — no change needed there.

const outputPath = resolve(__dirname, '../worker/src/eco-epd.json');
writeFileSync(outputPath, JSON.stringify(db), 'utf-8');

const keys = Object.keys(db);
const sizeKb = Math.round(readFileSync(outputPath).length / 1024);
console.log(`Parsed ${count} entries from TSV`);
console.log(`${keys.length} unique EPD positions (some share positions)`);
console.log(`Wrote ${outputPath} (${sizeKb} KB)`);
