#!/usr/bin/env node

/**
 * Downloads the lichess chess-openings TSV files and generates src/eco-data.js
 *
 * Usage: node scripts/build-eco.js
 *
 * Data source: https://github.com/lichess-org/chess-openings
 * Format: TSV with columns: eco, name, pgn
 */

const BASE_URL = 'https://raw.githubusercontent.com/lichess-org/chess-openings/master';
const FILES = ['a.tsv', 'b.tsv', 'c.tsv', 'd.tsv', 'e.tsv'];
const OUTPUT = new URL('../src/eco-data.js', import.meta.url).pathname;

import { writeFileSync } from 'fs';

async function fetchTsv(filename) {
    const url = `${BASE_URL}/${filename}`;
    console.log(`Fetching ${url}...`);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Failed to fetch ${filename}: ${res.status}`);
    return res.text();
}

function parseTsv(text) {
    const lines = text.trim().split('\n');
    // Skip header line: "eco\tname\tpgn"
    const entries = [];
    for (let i = 1; i < lines.length; i++) {
        const parts = lines[i].split('\t');
        if (parts.length < 3) continue;
        entries.push({
            eco: parts[0].trim(),
            name: parts[1].trim(),
            moves: parts[2].trim(),
        });
    }
    return entries;
}

async function main() {
    const allEntries = [];

    for (const file of FILES) {
        const text = await fetchTsv(file);
        const entries = parseTsv(text);
        allEntries.push(...entries);
        console.log(`  ${file}: ${entries.length} entries`);
    }

    console.log(`Total: ${allEntries.length} entries`);

    // Group by ECO code, sort each group by moves length descending (longest first for prefix matching)
    const grouped = {};
    for (const entry of allEntries) {
        if (!grouped[entry.eco]) grouped[entry.eco] = [];
        grouped[entry.eco].push({ name: entry.name, moves: entry.moves });
    }

    for (const eco of Object.keys(grouped)) {
        grouped[eco].sort((a, b) => b.moves.length - a.moves.length);
    }

    // Sort ECO codes for deterministic output
    const sortedKeys = Object.keys(grouped).sort();
    const sortedDb = {};
    for (const key of sortedKeys) {
        sortedDb[key] = grouped[key];
    }

    const js = `// Auto-generated by scripts/build-eco.js — do not edit manually
// Source: https://github.com/lichess-org/chess-openings
// ${allEntries.length} openings across ${sortedKeys.length} ECO codes

export const ECO_DB = ${JSON.stringify(sortedDb)};
`;

    writeFileSync(OUTPUT, js, 'utf-8');
    console.log(`Wrote ${OUTPUT} (${sortedKeys.length} ECO codes)`);
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
